# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=/opt/puppetlabs/bin:/opt/puppetlabs/puppetlabs-bootstrap/bin:$PATH:$HOME/bin

export PATH
unset USERNAME
