# .bashrc

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

if [[ -f "${C_CUSTROOT:-${HOME}/customization}"/shell/bourne_terminal ]]
then
    source "${C_CUSTROOT:-${HOME}/customization}"/shell/bourne_terminal
fi

PATH="${PATH}:/usr/local/git/bin:/usr/local/git/sbin"

PS1='\u@\h:\w\$ '
